eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
    hostname: ${CF_INSTANCE_IP:localhost}
    nonSecurePort: ${CF_INSTANCE_PORT:${PORT:${server.port:8888}}}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

testvar: testvar
